### ISSUE TITLE
Generate comprehensive comparisons between RNAseq, Mutation, and Clinical Matrix

### ISSUE THREAD

**Issue by gwaybio** [cognoma/cancer-data#17]
We need to generate a comparison between the sample IDs that exist in all three data sources. It will be good to subset the clinical matrix to only samples that are measured by RNAseq and to file a pull request with this report.

**Comment by gwaybio** [comment]
@mike19106

**Comment by dhimmel** [comment]
You should be able to use the sample_ids from [`data/subset/expression-matrix-all-samples.tsv`](https://github.com/cognoma/cancer-data/blob/master/data/subset/expression-matrix-all-samples.tsv), which are the intersect of expression and mutation samples.

Also I usually wait till the last moment to drop samples, meaning we probably could process the clinical matrix without this information?
