### ISSUE TITLE
Licensing of the Xena TCGA Pan-Cancer Data

### ISSUE THREAD

**Issue by dhimmel** [cognoma/cancer-data#3]
Currently, the licensing of the [TCGA Pan-Cancer Data](https://genome-cancer.soe.ucsc.edu/proj/site/xena/datapages/?cohort%3DTCGA%2520Pan-Cancer%2520%28PANCAN%29) available via UCSC's [Xena Browser](http://xena.ucsc.edu/) is unclear. I've [messaged their listserv](https://groups.google.com/d/msg/ucsc-cancer-genomics-browser/eg6nJOFSefw/Kd2JtLN3AQAJ) and will update this issue with any progress.

**Comment by dhimmel** [comment]
[According to](https://groups.google.com/d/msg/ucsc-cancer-genomics-browser/eg6nJOFSefw/tWfef0F6AQAJ) Mary Goldman from the UCSC Xena Browser team:

> There is no license for our data, only our software.

They seem to intend for other people to reuse their datasets with attribution, although they haven't actually provided a license allowing people to do so. It seems that part of the issue [may be uncertainty](https://groups.google.com/d/msg/ucsc-cancer-genomics-browser/eg6nJOFSefw/zMY8pSIVAgAJ) over the licensing of the TCGA data they incorporate.

Therefore I emailed `tcga@mail.nih.gov` about the copyright status and licensing of the TCGA Open Access [data tier](https://tcga-data.nci.nih.gov/docs/publications/tcga/accesstiers.html). We'll revisit this issue after hearing back from TCGA.

**Comment by dhimmel** [comment]
# TCGA Open Acess Data Tier is Public Domain

Amy Blum, a Communications Manager at the NCI, [responded to my inquiry](https://github.com/cognoma/cancer-data/files/370246/TCGA-public-domain-email.pdf) regarding the TCGA's copyright status. According to her, the Open Access Data Tier is in the public domain. This is great news as it means anyone can use this data however they want, without having to scrutinize its licensing.

**Comment by dhimmel** [comment]
I'm updating this discussion with a message @maryjgoldman posted to the [Xena Browser Mailing List](https://groups.google.com/d/msg/ucsc-cancer-genomics-browser/eg6nJOFSefw/E6kZ7QQ8BAAJ):

> The person who is in charge or our licenses is out this week but will be back on Monday. I'm guessing this is no problem and am looking at this license: http://opendatacommons.org/licenses/by/summary/. I will make sure this is on his desk on Monday morning for his review.

@maryjgoldman just checking in. Any progress on the open licensing front?

**Comment by maryjgoldman** [comment]
@jingchunzhu I believe we agreed to put our processed TCGA data in the public domain as well. This does not apply to our other datasets from other data providers.

**Comment by jingchunzhu** [comment]
I think the cognoma team contacted TCGA to ask if the public tier data is considered public domain data, and TCGA said yes.

Since Xena team does not put any restriction on people to use our processed version data, the processed TCGA becomes public domain data automatically.

For other datasets, we don't have the personnel resource to contact each source explicitly, so we can't just say xena processed data is automatically public domain.

Jing

**Comment by dhimmel** [comment]
@maryjgoldman and @jingchunzhu thanks so much for clearing this up. I'll treat the Xena Browser TCGA data as public domain.

You may want to consider adding a field your JSON metadata for TCGA-derives datasets like:

``` json
"license": "https://creativecommons.org/publicdomain/zero/1.0/"
```

This would provide exception clarity on a dataset-by-dataset level!

Cheers, Daniel!
